### ISSUE TITLE
Password included

### ISSUE THREAD

**Issue by anthonyryan1** [davepetrov/Gym-Booking-Discord-Bot#2]
Just a heads up @davepetrov it looks like your password made it into the repo here.

Given I don't see a way to change it with fit4less, you'll likely want to patch the git history and force push it here.

There's a decent example of git filter-branch here:
https://stackoverflow.com/questions/7194939/git-change-one-line-in-file-for-the-complete-history

Thanks for posting this, it'll help me get to bed earlier.

**Comment by davepetrov** [comment]
Thank you Anthony for the find. I should have looked much closer when made my first commit!
